//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syntezator_Krawczyka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syntezator_Krawczyka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIFF¬XWAVEfmt D¬XdataX.
        /// </summary>
        internal static string czysty {
            get {
                return ResourceManager.GetString("czysty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;file tempo=&quot;120&quot;&gt;
        ///  &lt;name lang=&quot;pl&quot;&gt;Przykład&lt;/name&gt;
        ///  &lt;name lang=&quot;en&quot;&gt;Example&lt;/name&gt;
        ///  &lt;sound type=&quot;syntezator-krawczyka&quot; id=&quot;proste&quot;&gt;
        ///    &lt;module type=&quot;sekwencer&quot; id=&quot;player1&quot; output=&quot;oscylator1&quot;&gt;&lt;/module&gt;
        ///    &lt;module type=&quot;oscylator&quot; id=&quot;oscylator1&quot; output=&quot;granie1&quot;&gt;&lt;/module&gt;
        ///    &lt;module type=&quot;granie&quot; id=&quot;granie1&quot;&gt;&lt;/module&gt;
        ///  &lt;/sound&gt;
        ///&lt;/file&gt;.
        /// </summary>
        internal static string przyklad {
            get {
                return ResourceManager.GetString("przyklad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;file tempo=&quot;120&quot;&gt;
        ///  &lt;name lang=&quot;pl&quot;&gt;Przykład&lt;/name&gt;
        ///  &lt;name lang=&quot;en&quot;&gt;Example&lt;/name&gt;
        ///  &lt;sound type=&quot;syntezator-krawczyka&quot; id=&quot;pad&quot;&gt;
        ///    &lt;module type=&quot;sekwencer&quot; id=&quot;player1&quot; output=&quot;rozd1&quot; /&gt;
        ///    &lt;module type=&quot;rozdzielacz&quot; id=&quot;rozd1&quot; output=&quot;zmianawys1 zmianawys2 zmianawys3 zmianawys4&quot; /&gt;
        ///
        ///    &lt;module type=&quot;zmianaWysokości&quot; id=&quot;zmianawys1&quot; output=&quot;oscylator1&quot;/&gt;
        ///    &lt;module type=&quot;oscylator&quot; id=&quot;oscylator1&quot; output=&quot;adsr1&quot; typ=&quot;piłokształtna&quot; A=&quot;0&quot; D=&quot;0&quot; S=&quot;1&quot; R=&quot;0&quot; bala [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string przyklad2 {
            get {
                return ResourceManager.GetString("przyklad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;file tempo=&quot;120&quot;&gt;
        ///  &lt;name lang=&quot;pl&quot;&gt;Przykład&lt;/name&gt;
        ///  &lt;name lang=&quot;en&quot;&gt;Example&lt;/name&gt;
        ///  &lt;sound type=&quot;syntezator-krawczyka&quot; id=&quot;pad&quot;&gt;
        ///    &lt;module type=&quot;sekwencer&quot; id=&quot;player1&quot; output=&quot;rozd1&quot; /&gt;
        ///    &lt;module type=&quot;rozdzielacz&quot; id=&quot;rozd1&quot; output=&quot;zmianawys1 zmianawys2 zmianawys3 zmianawys4&quot; /&gt;
        ///
        ///    &lt;module type=&quot;zmianaWysokości&quot; id=&quot;zmianawys1&quot; output=&quot;oscylator1&quot;/&gt;
        ///    &lt;module type=&quot;oscylator&quot; id=&quot;oscylator1&quot; output=&quot;adsr1&quot; typ=&quot;piłokształtna&quot; A=&quot;0&quot; D=&quot;0&quot; S=&quot;1&quot; R=&quot;0&quot; bala [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string przyklad3 {
            get {
                return ResourceManager.GetString("przyklad3", resourceCulture);
            }
        }
    }
}
